openapi: 3.0.0
info:
  title: CICK Playlister API
  description: Simple API to retrieve track data for public playlists
  version: 0.0.1
externalDocs:
  description: Source code, feature requests, and bug reports.
  url: https://github.com/captaincoordinates/cick-playlister
components:
  responses:

paths:
  /spotify/{playlistIdentifier}:
    get:

      responses:
        "200":

  /healthz:
    get:
      tags:
        - Health Check
      responses:
        "200":
          description: Healthy
